from __future__ import annotations

import csv
from collections.abc import Iterable
from pathlib import Path
from typing import Any

CSV_FIELDS: dict[str, list[str]] = {
    "album_metadata_issues.csv": [
        "album_key",
        "album_id",
        "artist",
        "album",
        "year",
        "track_count",
        "track_ids",
        "track_titles",
        "paths",
        "related_album_ids",
        "related_album_keys",
        "signals",
    ],
    "album_library_coverage.csv": [
        "user",
        "album_id",
        "artist",
        "album",
        "added_at",
        "total_tracks",
        "tracks_heard",
        "tracks_unheard",
        "heard_pct",
        "play_count",
        "last_played",
        "year",
        "genre",
    ],
    "album_completion.csv": [
        "user",
        "album_key",
        "album_id",
        "artist",
        "album",
        "release_year",
        "library_tracks",
        "album_runs",
        "probable_full_plays",
        "near_complete_runs",
        "started_from_beginning",
        "probable_abandons",
        "avg_completion_pct",
        "median_completion_pct",
        "avg_sequential_pct",
        "favorite_stop_track",
        "full_play_rate_pct",
    ],
    "album_eras.csv": [
        "user",
        "level",
        "start_week",
        "end_week",
        "weeks",
        "artist",
        "album",
        "dominant_plays",
        "period_total",
        "avg_share_pct",
    ],
    "album_resume_events.csv": [
        "thread_id",
        "user",
        "artist",
        "album",
        "pause_hours",
        "from_time",
        "to_time",
        "from_position",
        "to_position",
        "from_title",
        "to_title",
        "interleaved_scrobbles",
        "metadata_confidence",
    ],
    "album_resurrections.csv": [
        "user",
        "silent_days",
        "before",
        "return",
        "artist",
        "album",
        "before_completion_pct",
        "return_completion_pct",
        "album_key",
    ],
    "album_runs.csv": [
        "run_id",
        "user",
        "start",
        "end",
        "span_minutes",
        "album_key",
        "album_id",
        "artist",
        "album",
        "release_year",
        "library_tracks",
        "scrobbles",
        "unique_tracks",
        "completion_pct",
        "sequential_pct",
        "forward_pct",
        "first_position",
        "last_position",
        "starts_at_beginning",
        "reaches_end",
        "complete_like",
        "full_pass",
        "meaningful",
        "status",
        "listening_mode",
        "stop_track",
    ],
    "album_thread_completion.csv": [
        "user",
        "album_key",
        "album_id",
        "artist",
        "album",
        "release_year",
        "library_tracks",
        "logical_threads",
        "probable_full_plays",
        "resumed_threads",
        "probable_abandons_after_window",
        "avg_coverage_pct",
        "median_coverage_pct",
        "avg_ordered_coverage_pct",
        "avg_coverage_24h_pct",
        "avg_coverage_48h_pct",
        "full_play_rate_pct",
    ],
    "album_thread_resurrections.csv": [
        "user",
        "silent_days",
        "before",
        "return",
        "artist",
        "album",
        "before_coverage_pct",
        "return_coverage_pct",
        "album_key",
    ],
    "album_threads.csv": [
        "thread_id",
        "user",
        "start",
        "end",
        "span_hours",
        "album_key",
        "album_id",
        "artist",
        "album",
        "release_year",
        "library_tracks",
        "scrobbles",
        "unique_tracks",
        "coverage_pct",
        "ordered_coverage_pct",
        "coverage_24h_pct",
        "ordered_coverage_24h_pct",
        "coverage_48h_pct",
        "ordered_coverage_48h_pct",
        "first_position",
        "last_position",
        "starts_at_beginning",
        "reaches_end",
        "resume_count",
        "max_pause_hours",
        "complete_like",
        "full_thread",
        "meaningful",
        "status",
        "metadata_confidence",
    ],
    "album_transitions.csv": [
        "user",
        "times",
        "from_artist",
        "from_album",
        "to_artist",
        "to_album",
        "from_album_key",
        "to_album_key",
    ],
    "artist_depth.csv": [
        "artist",
        "plays",
        "library_tracks",
        "heard_tracks",
        "track_breadth_pct",
        "library_albums",
        "heard_albums",
        "album_breadth_pct",
        "top_album_share_pct",
        "top_track_share_pct",
    ],
    "artist_eras.csv": [
        "user",
        "level",
        "start_week",
        "end_week",
        "weeks",
        "artist",
        "album",
        "dominant_plays",
        "period_total",
        "avg_share_pct",
    ],
    "context_jumps.csv": [
        "user",
        "at",
        "score",
        "confidence",
        "from_artist",
        "from_title",
        "from_genre",
        "from_year",
        "to_artist",
        "to_title",
        "to_genre",
        "to_year",
        "evidence",
    ],
    "discoveries.csv": [
        "user",
        "plays",
        "lifespan_days",
        "first_play",
        "last_play",
        "artist",
        "title",
        "album",
        "track_id",
    ],
    "historical_vs_recent_albums.csv": [
        "user",
        "artist",
        "album",
        "album_key",
        "historical_total",
        "recent_scrobbles",
        "estimated_before_history",
        "recent_share_pct",
        "mismatch_tracks",
        "profile",
    ],
    "historical_vs_recent_artists.csv": [
        "user",
        "artist",
        "historical_total",
        "recent_scrobbles",
        "estimated_before_history",
        "recent_share_pct",
        "mismatch_tracks",
        "profile",
    ],
    "legacy_playcounts.csv": [
        "user",
        "play_count",
        "last_played",
        "track_id",
        "artist",
        "album",
        "title",
        "genre",
        "release_year",
    ],
    "metadata_issues.csv": [
        "track_id",
        "artist",
        "album",
        "disc_number",
        "track_number",
        "path_track_number",
        "title",
        "path",
        "title_path_similarity",
        "issues",
        "confidence",
    ],
    "monthly.csv": ["month", "plays"],
    "plays.csv": [
        "datetime",
        "date",
        "year",
        "month",
        "weekday",
        "hour",
        "user",
        "track_id",
        "artist",
        "album_artist",
        "album",
        "album_id",
        "disc_number",
        "track_number",
        "title",
        "genre",
        "release_year",
        "duration",
        "path",
        "mbid",
    ],
    "resurrections.csv": [
        "user",
        "silent_days",
        "before",
        "return",
        "artist",
        "title",
        "album",
        "track_id",
    ],
    "sessions.csv": [
        "session_id",
        "user",
        "start",
        "end",
        "span_minutes",
        "tracks",
        "unique_tracks",
        "estimated_music_minutes",
        "top_artist",
        "top_album",
        "top_genre",
    ],
    "top_tracks.csv": [
        "plays",
        "artist",
        "title",
        "album",
        "genre",
        "release_year",
        "track_id",
    ],
    "track_pairs.csv": [
        "user",
        "times",
        "from_artist",
        "from_title",
        "to_artist",
        "to_title",
        "from_track_id",
        "to_track_id",
    ],
    "weekly_album_dominance.csv": [
        "user",
        "year",
        "week",
        "week_start",
        "plays",
        "week_total",
        "share_pct",
        "artist",
        "album",
        "entity_key",
    ],
    "weekly_obsessions.csv": [
        "year",
        "week",
        "user",
        "plays",
        "week_total",
        "share",
        "artist",
        "title",
        "album",
        "track_id",
    ],
}


def write_csv(
    path: Path,
    rows: Iterable[dict[str, Any]],
    fieldnames: list[str],
) -> None:
    with path.open("w", encoding="utf-8", newline="") as output_file:
        writer = csv.DictWriter(output_file, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key, "") for key in fieldnames})


def write_export(path: Path, rows: Iterable[dict[str, Any]]) -> None:
    write_csv(path, rows, CSV_FIELDS[path.name])
